services:
  - type: web
    name: scorpions-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production